### PR TITLE
Add alog extension tip py

### PR DESCRIPTION
**Pull request by gkumbhat**
## Description

Add alog code generation extension in readme for python.

## Changes

Update readme with vscode extension tip

## Testing

N/A

## Related Issue(s)

N/A

### CODE REVIEW

**Review by gabe-l-hart — APPROVED** [review]
Very nice!

**Comment by gabe-l-hart** [comment]
@gkumbhat looks like it needs to be rebased with signed commits

**Comment by gkumbhat** [comment]
Oops, DCO.. I'll fix it

**Comment by gkumbhat** [comment]
Pushed!

**Pull request merged**
